### ISSUE TITLE
Could not recognize scene type!

### ISSUE THREAD

**Issue by AnudhinaDhanabalan** [turandai/gaussian_surfels#1]
I have followed all the steps properly with my own dataset. But during the training I am getting the error saying
Traceback (most recent call last):
  File "train.py", line 300, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 39, in training
    scene = Scene(dataset, gaussians, opt.camera_lr, shuffle=False, resolution_scales=[1, 2, 4])
  File "/home/ghost/gaussian_surfels-main/scene/__init__.py", line 55, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!

-should I mention the path of the dataset anywhere in the code or how can I solve this error?

**Comment by turandai** [comment]
Hi, this assertion is raised [here](https://github.com/turandai/gaussian_surfels/blob/e982367f25b3150a7c017455a2a3c556574cb835/scene/__init__.py#L45-L55). The dataloader now can only accept 3 types of input foramt: COLMAP format with an 'sparse' subfolder, the NeRF Blender format with an transforms_train.json file, and IDR format with a 'camera.npy' file. Please make sure to feed the right scene directory that contains the supported files. Hope this solves your problem.^_^

**Comment by turandai** [comment]
I just see you mentioned you are using your own dataset. In case your dataset is in currently unsupported format, maybe you need to either transform your dataset into the supported formats, or write a custom dataloader to read your image and camera data.

**Comment by AnudhinaDhanabalan** [comment]
yeah but my dataset directory has the "sparse" subfolder , eventhough it is showing the same error

**Comment by AnudhinaDhanabalan** [comment]
solved the mistake ,thanks for replying !!

**Comment by Wangyuxuan-jpg** [comment]
Hello, how did you solve this problem in the end? I have been troubled by this for a long time, thank you.
