### ISSUE TITLE
Are the camera parameters learnable?

### ISSUE THREAD

**Issue by alvin528** [turandai/gaussian_surfels#12]
Very impressive work! I'm trying to implement my ideas based on your code. But I noticed that the camera parameters q and T are nn.Parameter in https://github.com/turandai/gaussian_surfels/blob/654511a86573f311f4875c070fef8f58791a0548/scene/cameras.py#L60-L61

Are they updated with the network learning or just some unusable definitions?

**Comment by turandai** [comment]
Hi, we have tried to optimize the pose so the q and T are Parameter type, but they are not updating during the training as we set the default learning rate for them to 0. Although we have implemented the gradient chains from losses to the pose, this functionality has not yet fully tested, so we suggest to turn it off. However you are welcomed to do your expirements based on it.
