### ISSUE TITLE
Download Dataset Failed

### ISSUE THREAD

**Issue by zhiguotang5** [turandai/gaussian_surfels#14]
## Request to upload dataset to Google Drive due to slow download from OneDrive

 I’ve encountered an issue while attempting to download the dataset from the provided OneDrive link. The download speed has been exceedingly slow, and unfortunately, it has resulted in multiple failed download attempts. This seems to be a recurring problem for me, potentially due to geographical location or network congestion.

To ensure smooth access to this valuable resource for myself and potentially other users facing similar difficulties, I kindly request if the dataset could be uploaded to **Google Drive** as an alternative download option. Google Drive is generally known for its wider accessibility and more consistent download speeds across different regions.

_Thank you very much for considering this request. Your efforts in maintaining and sharing this dataset are highly appreciated._

**Comment by turandai** [comment]
Hi, I am sorry for your inconvenience. Unfortunatly, I can not provide google drive donwload link due to my limitted storage. Maybe you can try to download the dataset scene by scene.
