### ISSUE TITLE
GPU OOM problem

### ISSUE THREAD

**Issue by felix0903** [turandai/gaussian_surfels#18]
Why my GPU Memory-Usage increasing during the training progress.And it cause OOM when the training iteration is about 5k. My GPU Memory is 24G.

**Comment by turandai** [comment]
Hi, we use downsampled imges for warm-up training before 5k iters, the program would use more GPU memory after that. If your data contains hundreds of high-resolutin images, even 24G would be not enought. I hope this helps.

**Comment by felix0903** [comment]
Thanks for answering.Will you recomand I to reduce the number of images or to decrease the image resulution by some downsample methods?

**Comment by turandai** [comment]
I would first recommend decreasing the resolution, and you can also try reducing the nubmer of images if your traning views are densly sampled.

**Comment by felix0903** [comment]
Make sense. It's really helpful.
