### ISSUE TITLE
NerfSyntheticInfo

### ISSUE THREAD

**Issue by li1u** [turandai/gaussian_surfels#20]
Hello, I'm sorry to bother you. When I use your code to run input data containing transformers. json, it always stops midway and reports an error indicating it has been killed. Have you ever encountered this problem?

**Comment by turandai** [comment]
Hi, I haven’t met similar problems, could you provide more information?

**Comment by turandai** [comment]
Hi, I haven’t met similar problems, could you provide more information?

**Comment by li1u** [comment]
Hello, I have thought about it again and I think the main reason may be that my pictures were taken with multiple cameras, as I did not make any errors when processing data taken with a single camera. The only adjustment I have made to your code is the following step：
![image](https://github.com/turandai/gaussian_surfels/assets/97940633/e736afcb-af2c-4db3-98d8-a199b9357c54)

**Comment by li1u** [comment]
I just changed the reading position of fovx, I think it may not be enough, but I don't know where else to change. The code execution process only stopped suddenly midway without any other errors, so I am not sure what the specific problem is

**Comment by li1u** [comment]
Hello, I have another question to ask you, is it through controlling loss that you achieve mask operation? Is there any other way to handle it?
