### ISSUE TITLE
Slow decrease in loss

### ISSUE THREAD

**Issue by li1u** [turandai/gaussian_surfels#22]
Hello. When I was training other datasets, it performed well when I used the parameters run from colmap (converted to JSON format through colmap2nerf here). But when I use the standard internal and external parameter data provided in the dataset, its results become very strange.
![图片](https://github.com/turandai/gaussian_surfels/assets/97940633/158297ab-066e-49be-8dc7-ae3aeee544d8)
Above are the results obtained using colmap data.
![图片](https://github.com/turandai/gaussian_surfels/assets/97940633/1fba77c7-4b71-4d1f-a7e8-b2c46bc94e97)
The above is the result obtained from the camera parameters provided in the dataset.
![图片](https://github.com/turandai/gaussian_surfels/assets/97940633/b9c21471-9e3c-4399-8571-14dea8c7102b)

The biggest change after changing the parameters is a decrease in loss
![图片](https://github.com/turandai/gaussian_surfels/assets/97940633/70c2cb66-aa91-4092-a3b7-0267fd034c83)
At first, I thought it was a parameter issue, but when I changed the processing I did when reading the parameters above, he started reporting errors.
![图片](https://github.com/turandai/gaussian_surfels/assets/97940633/33d3b44b-8b1a-45e9-b5ce-81227fbec71e)
Like what others have encountered, so it seems that the parameters are not a problem because they can run normally without being changed。  Here are the rendering results I saved every 1000 times：

![图片](https://github.com/turandai/gaussian_surfels/assets/97940633/e0c3700c-24d2-44dc-a748-214e44919ad7)
![图片](https://github.com/turandai/gaussian_surfels/assets/97940633/cdc47cfc-56ec-42d3-a944-b20bfb3636a6)
![图片](https://github.com/turandai/gaussian_surfels/assets/97940633/b2a9f965-28b4-4799-9f3e-05970a4e93b1)
![test3001](https://github.com/turandai/gaussian_surfels/assets/97940633/e50e2222-611a-4fc7-b53e-b9e87bbed92e)
![test4001](https://github.com/turandai/gaussian_surfels/assets/97940633/87f9a99a-2524-4bd6-8d62-5f86643ea7a9)
![test5001](https://github.com/turandai/gaussian_surfels/assets/97940633/3811f9da-7d1b-4517-999d-ad3dab036e57)
![test6001](https://github.com/turandai/gaussian_surfels/assets/97940633/5802fe8b-abe5-4510-ac3c-589f676993c9)
![test7001](https://github.com/turandai/gaussian_surfels/assets/97940633/7ae687e8-8029-4101-8282-631fbd7ff2b2)
![test8001](https://github.com/turandai/gaussian_surfels/assets/97940633/cdc995fc-445a-45eb-b076-59227d275bc0)
![test9001](https://github.com/turandai/gaussian_surfels/assets/97940633/b24e88ed-a176-434b-b77f-aca728a29df9)
![test10001](https://github.com/turandai/gaussian_surfels/assets/97940633/5ea7b462-d3c4-4e5a-9b99-3eb6f5d79b59)
![test11001](https://github.com/turandai/gaussian_surfels/assets/97940633/4c67d961-a208-4662-b239-92ada2067421)
![test12001](https://github.com/turandai/gaussian_surfels/assets/97940633/37936762-b39e-4c8a-97f8-3b4a31f67e8d)

**Comment by turandai** [comment]
Hi, if I got you right, you are saying you get better results using colmap re-computed poses than the GT poses provided in your dataset? I wonder what is the format of the camera data in your dataset, and you may check if the cx, cy representing the principal points is properly loaded.

**Comment by li1u** [comment]
Yes, it is true that the values of cx and cy are incorrect. Thank you very much.
