### ISSUE TITLE
chamfer distance calculation for 3DGS

### ISSUE THREAD

**Issue by leeve818** [turandai/gaussian_surfels#23]
Hello,

Thanks for your awesome work! I am running the code to generate the result in the paper. I am facing issues getting the chamfer distance on 3DGS(splatting). I can only get the result on surfels. Could you please tell me the steps to generate the chamfer distance on 3DGS or share the code with me? Also, could you tell me how to generate the chamfer distance result on customized data after training and rendering on surfels?

Thanks.

**Comment by turandai** [comment]
For evaluation of 3DGS results, you first need to render the depth (also normal) map from the trained 3DGS model. Then the rendered depth map can be used to perform TSDF fusion or the Poisson Surface Reconstruction to extract the mesh surface. We did not apply the script for this process, but you can refer to ```render.py``` or other online open-source code for the above steps. As for evaluating Chamfer distance for custom data, you can refer to [this repo](https://github.com/jzhangbs/DTUeval-python).

**Comment by leeve818** [comment]
Could you please explain how to generate the depth map from original 3DGS implementation? Their rasterizer does not support rendering depth and normal map. If only keep Photometric loss in 3d gaussian surfels, will it be 3DGS?

**Comment by turandai** [comment]
Hi, yes the original repo does not provide depth rendering. You may also try to modify from our repo, but I am not sure if it works well. 
You can do it by:
1) set the ```self.surface = False``` [here](https://github.com/turandai/gaussian_surfels/blob/c1cbb40b6f048e7a13535c8e0fb210c8a8192966/arguments/__init__.py#L60), 2) like you said, only keep the photometric loss, 3), replace ```normal``` with ```d2n``` in [here](https://github.com/turandai/gaussian_surfels/blob/c1cbb40b6f048e7a13535c8e0fb210c8a8192966/render.py#L57) as 3DGS does not have an explicit normal, we use the normal derived from depth instead.

**Comment by leeve818** [comment]
I see. Thanks!

**Comment by JiatengLiu** [comment]
Hi, I also have a question, does this [line of code](https://github.com/turandai/gaussian_surfels/blob/149386375a64eb1aaaee9a7a257fa03ba296cd22/scene/gaussian_model.py#L182C15-L182C56) need to be commented out?
