### ISSUE TITLE
may be a mistake in calculating opacity mask?

### ISSUE THREAD

**Issue by CanCanZeng** [turandai/gaussian_surfels#24]
Hi @turandai , thank you for openning this great project, the result is really impressive!
There is one part I don't quite understand when reading the code. I think there may be a mistake. The mask should be calculated first and then 0.5 is subtracted. I don't know if my understanding is correct.
https://github.com/turandai/gaussian_surfels/blob/c1cbb40b6f048e7a13535c8e0fb210c8a8192966/train.py#L124

**Comment by turandai** [comment]
Hi, thank you very much. I have found this mistake too. However, I decide to keep it as all of our experiments are done with this mistake😂.

**Comment by CanCanZeng** [comment]
I corrected this mistake and just did a test on DTU scan24, it is hard to say the result becomes better. The PSNR value of the result decreased from 31.687 to 30.4016, which seems reasonable as the constraint became stronger after correction. The visualization results show that both have their own strengths and weaknesses. Before correction, a black mark appeared on the white roof, while after correction, a fuzzy mark appeared on the top of the tower.
![image](https://github.com/turandai/gaussian_surfels/assets/26817559/9b33dc36-b0e3-4c6a-a912-ad04d6adbef6)
![image](https://github.com/turandai/gaussian_surfels/assets/26817559/68a16048-fc1d-489d-b89d-1293aa8954e8)
(top is the original result, bottom is corrected)

**Comment by turandai** [comment]
You are right. I also tried to correct it, and I found the number of points drops significantly. This might be the main reason of the decreasing on PSNR. Also decreasing the weight of this opacity loss and the grad threshold for cloning to achieve comparable number of points can fill the performance gap. However, it was not becoming better either, that was the reason I keep it.

**Comment by CanCanZeng** [comment]
Thank you for your reminder. You said that the visualization result using SIBR_viewer is incorrect. Do you mean that the rendering result will be slightly different due to the difference in the ray-splat intersection algorithm? If this is the problem, I think it will not have much impact on me. When I visualize, I just use it to roughly check the noise level and reconstruction quality of the result. The data indicators such as PSNR are calculated from the render.py file in the code repository.

**Comment by turandai** [comment]
The most diffrent thing is we cull back-faced surfels during optimization and rendering, while the SIBR_viewer does not, we observe this results in increasing of floaters

**Comment by CanCanZeng** [comment]
This change should have a big impact. Can you share the SIBR_viewer code you modified? Or tell me how to modify it?

**Comment by turandai** [comment]
Hi, the line of code is [here](https://github.com/turandai/gaussian_surfels/blob/c1cbb40b6f048e7a13535c8e0fb210c8a8192966/submodules/diff-gaussian-rasterization/cuda_rasterizer/forward.cu#L277)

**Comment by CanCanZeng** [comment]
Thanks for your tip, I'm trying to figure it out
