### ISSUE TITLE
Possibility of GPU memory leak

### ISSUE THREAD

**Issue by CanCanZeng** [turandai/gaussian_surfels#26]
Hello, I found that when using render.py to calculate PSNR, the size of the video memory occupied kept increasing until OOM. In order to find the reason, I commented out all the parts after the render function https://github.com/turandai/gaussian_surfels/blob/c1cbb40b6f048e7a13535c8e0fb210c8a8192966/render.py#L39

but the video memory usage continued to increase until OOM. I suspect that there is a memory leak in the render function.
I am completely unfamiliar with cuda code, especially the cuda extension of pytorch. I hope the author or others can confirm whether there is a memory leak problem, or fix the problem of video memory growing all the time.

**Comment by turandai** [comment]
Hi, I am not sure about the reason, but you may try add this line ```view.to_cpu()``` to the end of the render [loop](https://github.com/turandai/gaussian_surfels/blob/c1cbb40b6f048e7a13535c8e0fb210c8a8192966/render.py#L37). Hope this solves your problem.

**Comment by CanCanZeng** [comment]
Yes, add `view.to_cpu()` solved my problem, many thanks!
