### ISSUE TITLE
About texture of mesh

### ISSUE THREAD

**Issue by ch1998** [turandai/gaussian_surfels#30]
After performing the complete training and rendering process, a nice mesh can be obtained, but the quality of  texture is very different from the quality on the project page. Do you use other methods to process it?

![image](https://github.com/turandai/gaussian_surfels/assets/37291486/ef05d94e-7992-4d25-b5b7-1eae1346f7ee)
![image](https://github.com/turandai/gaussian_surfels/assets/37291486/a73e57de-e4fe-4913-b678-fe1d9ab7f399)

**Comment by turandai** [comment]
Hi, the rgb images on the project page and paper are rendered through the Gaussian splatting pipeline, not the texture. Our method can only provide a coarse mesh for simple visualization.

**Comment by ch1998** [comment]
I understand, thanks for the recovery
