### ISSUE TITLE
Questions about calculating projection matrices

### ISSUE THREAD

**Issue by CanCanZeng** [turandai/gaussian_surfels#31]
Hi, I noticed that your CUDA code uses **full_proj_transform** https://github.com/turandai/gaussian_surfels/blob/c1cbb40b6f048e7a13535c8e0fb210c8a8192966/gaussian_renderer/__init__.py#L47

, which is derived from **projection_matrix** 
https://github.com/turandai/gaussian_surfels/blob/c1cbb40b6f048e7a13535c8e0fb210c8a8192966/scene/cameras.py#L97

but you does not take into account the **principal point** when calculating  **projection_matrix**
https://github.com/turandai/gaussian_surfels/blob/c1cbb40b6f048e7a13535c8e0fb210c8a8192966/scene/cameras.py#L72
https://github.com/turandai/gaussian_surfels/blob/c1cbb40b6f048e7a13535c8e0fb210c8a8192966/utils/graphics_utils.py#L66
So even though you used the principal point in the CUDA code, using the **full_project_matrix** may still result in imprecise results
https://github.com/turandai/gaussian_surfels/blob/c1cbb40b6f048e7a13535c8e0fb210c8a8192966/submodules/diff-gaussian-rasterization/cuda_rasterizer/forward.cu#L254

Is what I am considering correct?

**Comment by CanCanZeng** [comment]
Hi, I also noticed that you use principal point to recover **point_image**, my point is that the input **p_proj** is calculated from **full_proj_transform**, and **full_proj_transform** is not suitable for the imperfect pinhole camera, so the recovered point_image is still not accurate.

**Comment by turandai** [comment]
Hi, I think you are right. I didn't think deep here. I refered to [this](https://github.com/DNA-Rendering/DNA-Rendering/blob/114a6d05ace90d32fa0bfdb1b05849ec72bbd458/scripts/3DGS/utils/graphics_utils.py#L73-L95) and updated the [projection matrix](https://github.com/turandai/gaussian_surfels/blob/7cb0c402b9fb45cc33495de9dc74efbe08c90854/utils/graphics_utils.py#L91). Thank you very much for your remider! I am not very sure if this is properly fixed now, please feel free to get in touch.

**Comment by turandai** [comment]
Btw, I feel our research directions are quite close, we may use wechat for more direct contacts if you are convinient, my wechat id is turandai.

**Comment by CanCanZeng** [comment]
That's a good idea!
