### ISSUE TITLE
MVS point cloud slow

### ISSUE THREAD

**Issue by li1u** [turandai/gaussian_surfels#34]
Hello, when I use your code, I find that when I use randomly initialized point clouds, the speed is faster, but when I use other initial point clouds (mvs), the speed becomes significantly slower. Do you know why? Do you have a way to solve it?

**Comment by turandai** [comment]
I feel maybe the reason is your sfm point is significantly more than the random initialized ones. You van check the point count during training in the rightmost of the training bar.
