### ISSUE TITLE
There are regular twill patterns on the mesh surface

### ISSUE THREAD

**Issue by ch1998** [turandai/gaussian_surfels#35]
![image](https://github.com/turandai/gaussian_surfels/assets/37291486/7e90ada3-3333-45c7-8de6-f495f27a955c)

Hi，as shown in the figure above, the mesh exported by gaussian_surfels on the left has diagonal lines on the surface, which appeared in every set of data I tested.
I suspected at the beginning that it was a problem with the resampled point cloud in render, but because the resampled was too large, I used RGBD fusion to generate the point cloud. The point cloud visualization is as follows

![image](https://github.com/turandai/gaussian_surfels/assets/37291486/c25cb18b-8c05-4a18-94f1-a5f360aa7924)
The point cloud also has this problem. I think it is caused by the depth of the training, but I am not sure if this is correct. Is there any way to improve this problem?

**Comment by turandai** [comment]
Hi, if the point cloud also exhibit these lines, the problem might in the training. You may visualize the rendered normal to see if it also has such pattern. Also, please check the mesh without showing point color to make sure whether the lines come from the geometry or the color. If the resampled point cloud is too large, it is usually ok to skip some views under dense captures.

**Comment by ch1998** [comment]
> Hi, if the point cloud also exhibit these lines, the problem might in the training. You may visualize the rendered normal to see if it also has such pattern. Also, please check the mesh without showing point color to make sure whether the lines come from the geometry or the color. If the resampled point cloud is too large, it is usually ok to skip some views under dense captures.

Thanks for your reply. I have checked the mesh without color and I can confirm that these lines are caused by the mesh. The point cloud before generating the mesh can clearly see these lines.
![image](https://github.com/turandai/gaussian_surfels/assets/37291486/7eb72cb9-b049-4f70-83e5-de6398623263)

It is not possible to see whether such lines exist on the normal map.
![1720594028978](https://github.com/turandai/gaussian_surfels/assets/37291486/0977ed0f-7dd0-4255-ae42-188e28f01acb)

If the modification is made during the training phase, do you have any good suggestions? I have tried to modify the weight of the normal loss and the prediction model of the normal map, but neither can alleviate this problem well.

**Comment by turandai** [comment]
Hi, I see, I haven't met such issues before, but I think the problem might be the depth. You may also try to visualize the normal converted from depth ([this](https://github.com/turandai/gaussian_surfels/blob/09d5bad1774c65e2e03796a80f5f2c81f94d6dbf/train.py#L104)) to see if the pattern is introduced by the depth map.

**Comment by ch1998** [comment]
Thanks，I will try

**Comment by codersui713** [comment]
> > 嗨，如果点云也显示这些线，则问题可能出在训练中。您可以可视化渲染的法线，看看它是否也具有这样的图案。另外，请检查网格而不显示点颜色，以确保线条是来自几何体还是颜色。如果重新采样的点云太大，通常可以跳过密集捕获下的某些视图。
> 
> 感谢您的回复。我已经检查了没有颜色的网格，我可以确认这些线是由网格引起的。生成网格之前的点云可以清楚地看到这些线。 ![image](https://github.com/turandai/gaussian_surfels/assets/37291486/7eb72cb9-b049-4f70-83e5-de6398623263)
> 
> 无法在法线贴图上查看此类线条是否存在。 ![1720594028978](https://github.com/turandai/gaussian_surfels/assets/37291486/0977ed0f-7dd0-4255-ae42-188e28f01acb)
> 
> 如果在训练阶段进行修改，你有什么好的建议吗？我尝试修改法线损失的权重和法线图的预测模型，但都不能很好地缓解这个问题。

hello,Could you please explain how this normal map is generated, and specify in detail how the operation is carried out?
