### ISSUE TITLE
Principal point and custom dataset

### ISSUE THREAD

**Issue by robofar** [turandai/gaussian_surfels#36]
Hello.

I have some dataset, and I want to write camera class for it. When it comes to camera object, should `prcppoint` be expressed in pixels, or unitless? I saw in your code you divide `cx` and `cy` with `height` and `width`. So, which one is correct? (`cx`, `cy`, `width`, `height` are expressed in pixels):

1. `self.prcppoint = np.array([self.cx / self.image_width, self.cy / self.image_height])`
2. `self.prcppoint = np.array([self.cx, self.cy])`

**Comment by turandai** [comment]
Hi, I if your ```cx```, ```cy```, ```width```, ```height``` is in same unit, then the first one should be the correct express in this code.
