### ISSUE TITLE
Normal-Depth Consistency Loss make results worse

### ISSUE THREAD

**Issue by robofar** [turandai/gaussian_surfels#39]
Hello. I have sequence of images of a scene. When I train gaussian model with only RGB-L1 loss I get better rendering results then when I use for example RGB-L1 + Normal-Depth consistency loss (I use also opacity loss but do not have much impact). Mask loss Im not using and Prior normal from monocular network I am not estimating). Note that I estimate normals of point cloud when creating Gaussians (but not using your network, but directly on point cloud).

I am wondering why Normal-Depth consistency loss worsening rednering results, when you claim in the paper that it is main thing that gives good results. Can you please explain if you have any toughts?

**Comment by turandai** [comment]
Hi, the depth-normal consistency is essential for reconstruction and should also help with rendering in my experiments. Have you tried using the original way of calculating normal because I am not sure if the normal from point cloud works.
