### ISSUE TITLE
camera center

### ISSUE THREAD

**Issue by li1u** [turandai/gaussian_surfels#40]
Hello, I am amazed by the effect of your article. I hope you can help me solve a doubt. There are some data sets, such as renderme360, whose camera center is not half of the length and width of the image. How does 'prcppoint' solve this problem? I want to solve this problem by rewriting the projection matrix (the results of your paper are already very good, I rewrote it based on another article, and that article did not take into account the center offset)
![image](https://github.com/user-attachments/assets/ad6487e6-0856-426b-be01-23873a5a1888)
But the result is not ideal
![image](https://github.com/user-attachments/assets/de7d8006-af00-4add-92b4-23f4b115d064)
How do you use prcppoint? Or how do you rewrite diff-plane-rasterization?

**Comment by turandai** [comment]
Hi, I dealt with it [here](https://github.com/turandai/gaussian_surfels/blob/8123edca5f5fb8524129098d8970570880bf093c/utils/graphics_utils.py#L91). I remember I refered to DNA-Rendering code, and it seems working.

**Comment by mohitm1994** [comment]
@li1u how did you manage to convert renderme-360 camera coordinate to Gaussian splatting coordinate system?? some pointers would be useful.
