### ISSUE TITLE
Opacity loss reduces PSNR performance

### ISSUE THREAD

**Issue by gchhablani** [turandai/gaussian_surfels#44]
For some reason, adding the opacity loss reduces performance significantly.
If I comment out the loss calculation for opacity, then the PSNR increases from 15 to 20, and I get visibly decent results.

**Comment by turandai** [comment]
Hi, the opacity loss might push the opacity of semi-transparent points to 0, and those points will be pruned later. This can harm the rendering quality indeed as the number of total points would be much smaller. Please consider use a smaller weight or turning it off for cases where it does not perform well. I am sorry that the opacity loss generalizes not well on different scenes and is sensitive to the loss weight.
