### ISSUE TITLE
Process got killed during Poisson Meshing using custom data (CPU out of memory?)

### ISSUE THREAD

**Issue by PrimoKu** [turandai/gaussian_surfels#49]
Hi, thank you for making this amazing work public. There are some issues that I hope you could help me resolve.

I am using my own custom data for this project, and the training works perfectly—I can view the training results using the SIBR viewer. However, when I try to extract meshes using the `render.py` script, the first part (rendering) works well, but the second part (Poisson meshing) always gets stuck at 25%, and the process always got killed after, possibly because it consumes all of the CPU's memory.

Here are the images for the reference:
![0](https://github.com/user-attachments/assets/a16c9c3e-e8f8-4bfe-976a-12f0ed338967)
![1](https://github.com/user-attachments/assets/6e3be99a-0978-4362-a183-eac1bf6df279)

The data came from 1 minute and 39 seconds, a size of 45mb video, with sample rates of 4fps, that generates a total of 397 images. Is there any reason that might cause the issue? Could you suggest how to solve it?

Thank you.

**Comment by turandai** [comment]
Hi, hundres of images may be too many to process, you may try to reduce the total points sampled for reconstruction by two means: 1) skip some of the views in the main loop of render.py or 2) down sample the rendered images for sampling.

**Comment by siyanhu** [comment]
> Hi, thank you for making this amazing work public. There are some issues that I hope you could help me resolve.
> 
> I am using my own custom data for this project, and the training works perfectly—I can view the training results using the SIBR viewer. However, when I try to extract meshes using the `render.py` script, the first part (rendering) works well, but the second part (Poisson meshing) always gets stuck at 25%, and the process always got killed after, possibly because it consumes all of the CPU's memory.
> 
> Here are the images for the reference: ![0](https://github.com/user-attachments/assets/a16c9c3e-e8f8-4bfe-976a-12f0ed338967) ![1](https://github.com/user-attachments/assets/6e3be99a-0978-4362-a183-eac1bf6df279)
> 
> The data came from 1 minute and 39 seconds, a size of 45mb video, with sample rates of 4fps, that generates a total of 397 images. Is there any reason that might cause the issue? Could you suggest how to solve it?
> 
> Thank you.

I actually add another parameter to let poissom_mesh know how much data I would like to keep to generate a mesh, in case the memory isn't enough:

`def poisson_mesh(path, vtx_full, normal_full, color, depth, thrsh, keep_ratio=0.2):`


And the related downsampling process are like:

```
N = len(vtx_full)
keep_mask = torch.rand(N) < keep_ratio
vtx = vtx_full[keep_mask]
normal = normal_full[keep_mask]
```

Hope it helps!
