### ISSUE TITLE
Have you tested monodepth

### ISSUE THREAD

**Issue by SainingZhang** [turandai/gaussian_surfels#51]
Thank you for your work. I wonder have you tested monodepth? Which baseline did you use?

**Comment by turandai** [comment]
Yes, I have tested the monodepth from omnidata on DTU too, see no improvements on overall result. Monodepth must be helpful in larger scale indoor or outdoor scenes, but it can harm the details on little objects like those in DTU.

**Comment by SainingZhang** [comment]
Thank you very much. Which baseline do you use before? Depth anything?

**Comment by turandai** [comment]
I tested on monodepth from Omnidata. I believe models like depth anything will give better results.

**Comment by SainingZhang** [comment]
Thank you
