### ISSUE TITLE
How to obtain mesh and mesh normal images from the paper

### ISSUE THREAD

**Issue by lt-wang** [turandai/gaussian_surfels#52]
Thank you for your excellent work and for providing the code. I have a question regarding the results shown in the paper, specifically the mesh and mesh normal images.

Could you please provide more details on how to obtain the mesh and mesh normal visualizations ? Are there any specific steps or tools in the code that need to be used to generate these visualizations?

I would really appreciate any guidance or scripts you could share to help me reproduce those results.

**Comment by turandai** [comment]
Hi, thank you very much for your interest. The visualizations are obtained by running ```render.py```, it renders and saves rgb, normal, and depth images, and also reconstruct a ```.ply``` mesh model that can be opended by any 3d viewer.
