### ISSUE TITLE
Blendmvs dataset list

### ISSUE THREAD

**Issue by Wuuu3511** [turandai/gaussian_surfels#53]
Thank you for your excellent work!
Could you please let me know which scenes from the original dataset you selected for the preprocessed blendmvs dataset? Since you modified the names, I can’t identify them. Could you provide the original list?

**Comment by turandai** [comment]
Hi, here is the original scene list:
59d2657f82ca7774b1ec081d: basketball
5bf3a82cd439231948877aed: bear
5c1dbf200843bc542d8ef8c4: bread
5c34300a73a8df509add216d: camera
5a969eea91dfc339a9a3ad2c: clock
5b22269758e2823a67a3bd03: cow
5c1af2e2bee9a723c963d019: dog
5a3cb4e4270f0e3f14d12f43: doll
5c189f2326173c3a09ed7ef3: dragon
59350ca084b7f26bf5ce6eb8: durian
599aa591d5b41f366fed0d58: fountain
5c0d13b795da9479e12e2ee9: gundam
5c20ca3a0843bc542d94e3e2: house
5b21e18c58e2823a67a10dd8: jade
5bf7d63575c26f32dbf7413b: man
5b192eb2170cf166458ff886: monster
59f363a8b45be22330016cad: sculpture
5adc6bd52430a05ecb2ffb85: stone

**Comment by Wuuu3511** [comment]
Thank you so much!
