### ISSUE TITLE
How long for Poisson meshing?

### ISSUE THREAD

**Issue by brianneoberson** [turandai/gaussian_surfels#6]
Hello, 

first of all, thank you for your work! I am excited to test your code on my dataset. 

I first tried testing it on a DTU scene (scan37) and the training ran smoothly and was pretty quick. However I am now trying to extract the mesh by running the render.py script as you mention but once it gets to the poisson meshing part, it seems to get stuck. How long is it supposed to take for the poisson meshing to complete? The script seems to now be stuck at: 
`Poisson meshing:  25%|████████████████                                                | 1/4 [00:00<00:00, 64527.75it/s]` 
for the past 20 minutes. Is this normal? How long should it take? 

Best regards, 
Brianne

**Comment by turandai** [comment]
Hi, for small object like in DTU, the meshing process normaly takes around 3-5 minutes (using depth of 10) in my case. Larger or noisy-er scenes would take longer in general. 20 minutes seems abnormal, maybe you can try with a smaller depth first to test if the pymeshlab works well  on your machine. I hope this helps.

**Comment by brianneoberson** [comment]
Thank you for the quick response!
I realized I had another process running in the background which was using up the CPU, that's why it was stuck. After killing that process the meshing was pretty quick.
