### ISSUE TITLE
Guidance Needed for Training on Custom Data

### ISSUE THREAD

**Issue by aeskandari68** [turandai/gaussian_surfels#8]
I'm encountering some issues while attempting to train on custom data using gaussian surfels. Here's my process so far:

1. I've generated the COLMAP positions for my custom data and stored my images in the `image` directory. The COLMAP sparse model is also located at the same level as the image directory. `/mnt/f/check/dff_100/sparse/0`
2. Upon running the command `python estimate_normal.py --img_path /mnt/f/check/dff_100/image`, a folder called `normal` is created at the same level as the image folder, i.e., `/mnt/f/check/dff_100/normal`, containing the same number of images as in the `image` folder. It seems that Omnidata is functioning correctly up to this point.

However, when I attempt to proceed to the training phase using the command `python train.py -s /mnt/f/check/dff_100`, I encounter the following error:
![Screenshot 2024-05-05 184117](https://github.com/turandai/gaussian_surfels/assets/91352576/687b069f-7f4a-4c54-952c-36f5c74aa278)

Could someone provide guidance on how to successfully train the model using my own custom data?

**Comment by turandai** [comment]
Hi, it seems the code has read your images properly, but fail to load the SfM point cloud from COLMAP, so ends up having 'None' value for point cloud.  The point cloud reading code is [here](https://github.com/turandai/gaussian_surfels/blob/f053a7139d3a93893ac6cbd0afa68250a29d1704/scene/dataset_readers.py#L201-L224). You may check if the 'points3D.bin' or 'points3D.txt' if properly generated by COLMAP.

**Comment by aeskandari68** [comment]
Thank you for your assistance. I managed to resolve the issue. However, I have a few follow-up questions:

1. I noticed during training that `dataset.with_mask=True`. Does your method require masks during training?

2. Could you please explain the purpose of the following line?https://github.com/turandai/gaussian_surfels/blob/fa0abeae1a02888db40d4c1b30607a74a431a875/train.py#L105 When I attempted to train the model using my custom data, I encountered a size mismatch between `mono` and `mask_gt`. To resolve this issue, I manually set `mono` to `None`. However, I'm curious about the purpose of this matrix multiplication. See the screenshot below for reference:
   ![Screenshot 2024-05-06 090422](https://github.com/turandai/gaussian_surfels/assets/91352576/37cf248f-0961-4019-83f9-5404a2ea8748)

3. To address any potential issues from points 1 and 2, I manually set `dataset.with_mask=False` and `mono=None`. However, during training, I encountered another issue. The initial 5000 iterations proceeded quickly, with Gaussian point clouds being saved in approximately 2 minutes. However, subsequent training became extremely slow, taking 11 hours and 43 minutes to reach iteration 11300. Is this level of slowdown typical in your pipeline, or am I possibly approaching the training process incorrectly?
   ![image](https://github.com/turandai/gaussian_surfels/assets/91352576/e5c9aa3f-ee7f-4f24-95f5-3e6a2cbafa05)

Thank you for your help and guidance.

**Comment by turandai** [comment]
Hi, 1) the mask is not mandatory, you can set the with_mask parameter to False in arguments/__init__.py, 2) this is a resizing bug, it should be fixed now, 3) the first 5k iters is quicker as they uses downsampled images. There will be a slow down after 5k iters, but far not that dramatic. I assume there is something wrong in your training process, but I am sorry that I can not tell what it is for now. Maybe you can check the test/test.png that records the training process to see if it provides more information of the potential problem. I hope this helps.

**Comment by aeskandari68** [comment]
Thank you for your response. I have checked the test image and it seems to be very smooth, and nice (rendered, normals, and depth). 

To see if there are any significant changes in the training time, I will perform the following scenarios: 

1. I will check the images and run COLMAP again. 

2. I will reduce the number of images from 300 to 100. 

3. I will downsample the images by 50% from 1080x1920. 

4. I will generate a heatmap, which may help the model to focus on the object and reduce the training time. 

I am planning to use "segment anything" from the meta to generate a mask. If you have any suggestions on which method I should use, I would really appreciate it. I will update you here if I find the problem.

**Comment by turandai** [comment]
Oh, I see, you are training hundreds of high-resolution images. I have not test such settings before, there might be unexpected issues indeed. For generating masks, it might be quite time-consuming even with the help of SAM. I think the use of masks would not significantly slow down the training in general, and maybe the downsampling will solve the problem.
