### ISSUE TITLE
Having True defaults for store_true variables makes the arg always be True

### ISSUE THREAD

**Issue by Parskatt** [turandai/gaussian_surfels#9]
See here: https://github.com/turandai/gaussian_surfels/blob/main/arguments/__init__.py#L19

For example, with_mask will always be true: https://github.com/turandai/gaussian_surfels/blob/main/arguments/__init__.py#L61

I had to set it manually to False in the init.

**Comment by turandai** [comment]
Hi, I am sorry, it was a bug with the --with_mask argument, it should be fixed now. Please use the '--use_mask 1/0' to try run with/without mask.
